package com.OnlineToyStore.Sllit.model;

import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
// ENCAPSULATION — all fields are private, accessed via getters/setters (generated by Lombok @Data)
public class Supplier {

    private String supplierId;
    private String name;
    private String contactPerson;
    private String email;
    private String phone;
    private String address;
    private String supplyCategory; // EDUCATIONAL, ELECTRONIC, SOFT, GENERAL, ALL

    // ABSTRACTION — the restock logic is hidden inside this method
    // POLYMORPHISM — this method is overridden in LocalSupplier and ImportedSupplier
    public String getRestockMethod() {
        return "Standard restock order";
    }

    // FILE HANDLING — converts this object to one line in suppliers.txt
    // Format: supplierId|name|contactPerson|email|phone|address|supplyCategory
    public String toFileString() {
        return supplierId + "|" +
                name + "|" +
                (contactPerson != null ? contactPerson : "") + "|" +
                (email != null ? email : "") + "|" +
                (phone != null ? phone : "") + "|" +
                (address != null ? address : "") + "|" +
                (supplyCategory != null ? supplyCategory : "ALL");
    }

    // FILE HANDLING — reads one line from suppliers.txt and creates a Supplier object
    public static Supplier fromFileString(String line) {
        String[] parts = line.split("\\|", -1);

        Supplier s = new Supplier();
        s.setSupplierId(parts[0]);
        s.setName(parts[1]);
        s.setContactPerson(parts.length > 2 ? parts[2] : "");
        s.setEmail(parts.length > 3 ? parts[3] : "");
        s.setPhone(parts.length > 4 ? parts[4] : "");
        s.setAddress(parts.length > 5 ? parts[5] : "");
        s.setSupplyCategory(parts.length > 6 ? parts[6] : "ALL");

        return s;
    }
}